(() => {
  const DB_NAME="brain2-extension-vault-v6";const DB_VERSION=1;const STORE="queue";let dbPromise;
  function open(){if(dbPromise)return dbPromise;dbPromise=new Promise((resolve,reject)=>{const request=indexedDB.open(DB_NAME,DB_VERSION);request.onupgradeneeded=()=>{const db=request.result;if(!db.objectStoreNames.contains(STORE)){const store=db.createObjectStore(STORE,{keyPath:"seq",autoIncrement:true});store.createIndex("byRecordId","recordId",{unique:true});store.createIndex("byQueuedAt","queuedAt");}};request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error||new Error("Unable to open Brain2 extension queue"));});return dbPromise;}
  async function add(recordId,box){const db=await open();return new Promise((resolve,reject)=>{const tx=db.transaction(STORE,"readwrite");const request=tx.objectStore(STORE).add({recordId,box,queuedAt:new Date().toISOString()});request.onsuccess=()=>resolve(request.result);request.onerror=()=>{if(request.error?.name==="ConstraintError")resolve(null);else reject(request.error);};tx.onabort=()=>{if(tx.error?.name!=="ConstraintError")reject(tx.error||new Error("Queue add aborted"));};});}
  async function list(limit=250){const db=await open();return new Promise((resolve,reject)=>{const tx=db.transaction(STORE,"readonly");const store=tx.objectStore(STORE);const out=[];const request=store.openCursor();request.onsuccess=()=>{const cursor=request.result;if(!cursor||out.length>=limit){resolve(out);return;}out.push(cursor.value);cursor.continue();};request.onerror=()=>reject(request.error);});}
  async function count(){const db=await open();return new Promise((resolve,reject)=>{const request=db.transaction(STORE,"readonly").objectStore(STORE).count();request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error);});}
  async function ids(){const db=await open();return new Promise((resolve,reject)=>{const tx=db.transaction(STORE,"readonly");const request=tx.objectStore(STORE).index("byRecordId").getAllKeys();request.onsuccess=()=>resolve(request.result.map(String));request.onerror=()=>reject(request.error);});}
  async function remove(recordIds){if(!recordIds?.length)return 0;const db=await open();return new Promise((resolve,reject)=>{const tx=db.transaction(STORE,"readwrite");const index=tx.objectStore(STORE).index("byRecordId");let removed=0;for(const id of new Set(recordIds)){const request=index.getKey(id);request.onsuccess=()=>{if(request.result!==undefined){tx.objectStore(STORE).delete(request.result);removed++;}};}tx.oncomplete=()=>resolve(removed);tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error||new Error("Queue ACK aborted"));});}
  async function clear(){const db=await open();return new Promise((resolve,reject)=>{const tx=db.transaction(STORE,"readwrite");const store=tx.objectStore(STORE);const countReq=store.count();let count=0;countReq.onsuccess=()=>{count=countReq.result||0;store.clear();};tx.oncomplete=()=>resolve(count);tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error||new Error("Queue clear aborted"));});}
  globalThis.Brain2QueueDB={add,list,count,ids,remove,clear,kind:"indexeddb-v6"};
})();
