const $=(id)=>document.getElementById(id);
async function call(message){return chrome.runtime.sendMessage(message);}
function note(text,bad=false){$("message").textContent=text||"";$("message").className=`muted footer ${bad?"bad":"ok"}`;}
function fmtTime(value){if(!value)return "never";try{return new Date(value).toLocaleString();}catch{return String(value);}}
function setTab(name){const connection=name==="connection";$("tabConnection").classList.toggle("active",connection);$("tabCapture").classList.toggle("active",!connection);$("tabConnection").setAttribute("aria-selected",String(connection));$("tabCapture").setAttribute("aria-selected",String(!connection));$("panelConnection").classList.toggle("active",connection);$("panelCapture").classList.toggle("active",!connection);}
$("tabConnection").onclick=()=>setTab("connection");$("tabCapture").onclick=()=>setTab("capture");
function providerRow(name,health){const seen=health?.lastSeenAt||"";const capture=health?.lastCaptureAt||"";const error=health?.lastError||"";const active=Boolean(seen)&&Date.now()-Date.parse(seen)<15000;const turns=Number(health?.turnCount||0);const selector=health?.selectorMode||"none";const baseline=health?.baselineReady?`baseline ${health.baselineTurns||0}`:"baseline pending";const detail=error?`<span class="bad">${error}</span>`:`detected ${turns} turn${turns===1?"":"s"} · ${baseline}<br>last capture ${fmtTime(capture)} · ${selector}`;return `<div class="provider"><div><b>${name}</b><div class="muted">${detail}</div></div><span class="pill ${active?"ok":""}">${active?"WATCHING":"IDLE"}</span></div>`;}
function renderConnection(s){const connected=Boolean(s.connected),configured=Boolean(s.configured);const action=$("connectionAction");if(connected){$("website").innerHTML=`<span class="pill ok">CONNECTED</span><div style="margin-top:8px"><b>${s.origin}</b></div><div class="muted">Live handshake ${fmtTime(s.lastWebsiteSeenAt)} · delivered ${fmtTime(s.lastDeliveredAt)}</div>`;action.textContent="Disconnect Brain2";action.dataset.mode="disconnect";}else if(configured){$("website").innerHTML=`<span class="pill warn">CONNECTING</span><div style="margin-top:8px"><b>${s.origin}</b></div><div class="muted">Permission granted. Waiting for the live Brain2 handshake.</div>`;action.textContent="Disconnect Brain2";action.dataset.mode="disconnect";}else{$("website").innerHTML=`<span class="pill">DISCONNECTED</span><div class="muted" style="margin-top:8px">Open Brain2 AI Miner in a tab, then connect once.</div>`;action.textContent="Connect to active Brain2 tab";action.dataset.mode="connect";}$("retry").hidden=!configured||connected;$("connectionDiag").textContent=connected?`Bridge verified and live. installId=${s.installId} · heartbeat ${fmtTime(s.lastWebsiteSeenAt)}`:configured?`Origin is authorized but the live handshake is incomplete. ${s.lastError?`Last error: ${s.lastError}`:"The extension will keep retrying automatically."}`:"No Brain2 origin is configured.";}
async function refresh(){const s=await call({type:"BRAIN2_STATUS"});renderConnection(s);$("queue").textContent=`${s.queueCount||0} waiting`;$("queueHelp").textContent=(s.queueCount||0)>0?`${s.queueCount} captured turn${s.queueCount===1?"":"s"} stored locally until Brain2 ACKs them.`:"No queued captures. Existing visible history is baselined; only new completed turns are auto-captured.";$("vault").innerHTML=s.locked?`<span class="bad">Capture locked</span>`:`<span class="ok">Encrypted</span> · ${s.vaultMode||"device"}`;$("legacyVault").hidden=s.vaultMode!=="passphrase";const h=s.providerHealth||{};$("providers").innerHTML=providerRow("ChatGPT",h.chatgpt)+providerRow("Claude",h.claude)+providerRow("Gemini",h.gemini);}
async function waitForHandshake(origin,timeoutMs=7000){const start=Date.now();while(Date.now()-start<timeoutMs){await new Promise(r=>setTimeout(r,250));const s=await call({type:"BRAIN2_STATUS"});if(s.connected&&s.origin===origin)return s;}throw new Error("Permission was granted, but the Brain2 handshake did not complete. Keep the Brain2 tab open and use Retry handshake.");}
async function connectOnce(){note("");const [tab]=await chrome.tabs.query({active:true,currentWindow:true});if(!tab?.id||!tab.url)throw new Error("Open Brain2 AI Miner in the active tab first.");const url=new URL(tab.url);if(!/^https?:$/.test(url.protocol))throw new Error("The active tab is not an http(s) website.");const pattern=`${url.origin}/*`;const already=await chrome.permissions.contains({origins:[pattern]});if(!already){const granted=await chrome.permissions.request({origins:[pattern]});if(!granted)throw new Error("Permission for this Brain2 website was not granted.");}
  // IMPORTANT: Side Panel remains alive while Chrome asks for permission, so this continues automatically.
  const r=await call({type:"BRAIN2_CONFIG_ORIGIN",origin:url.origin,tabId:tab.id});if(!r?.ok)throw new Error(r?.error||"Could not configure Brain2 bridge.");await refresh();try{const s=await waitForHandshake(r.origin);note(`Connected to ${s.origin}.`);await refresh();}catch(error){note(error?.message||String(error),true);await refresh();}}
async function retryHandshake(){const s=await call({type:"BRAIN2_STATUS"});if(!s.configured||!s.origin)throw new Error("No Brain2 origin is configured.");const tabs=await chrome.tabs.query({url:`${s.origin}/*`});const tab=tabs.find(t=>t.active)||tabs[0];if(!tab?.id)throw new Error("Open the configured Brain2 website first.");const r=await call({type:"BRAIN2_CONFIG_ORIGIN",origin:s.origin,tabId:tab.id});if(!r?.ok)throw new Error(r?.error||"Could not restart Brain2 bridge.");const done=await waitForHandshake(s.origin);note(`Connected to ${done.origin}.`);await refresh();}
$("retry").onclick=()=>retryHandshake().catch(e=>{note(e?.message||String(e),true);refresh();});
$("connectionAction").onclick=async()=>{try{const s=await call({type:"BRAIN2_STATUS"});if(s.configured){const r=await call({type:"BRAIN2_DISCONNECT_WEBSITE"});note(r?.ok?"Disconnected from Brain2 website.":r?.error||"Disconnect failed",!r?.ok);await refresh();return;}await connectOnce();}catch(e){note(e?.message||String(e),true);await refresh();}};
$("open").onclick=async()=>{const s=await call({type:"BRAIN2_STATUS"});if(s.origin)return chrome.tabs.create({url:`${s.origin}/dashboard`});chrome.tabs.create({url:"https://"});note("Open your Brain2 deployment, then return here and press Connect.");};
$("testCapture").onclick=async()=>{try{const r=await call({type:"BRAIN2_CAPTURE_LATEST_ACTIVE"});if(!r?.ok)throw new Error(r?.error||"Capture test failed");note(`${r.provider}: latest ${r.role} turn ${r.duplicate?"was already queued/seen":"was queued"}. Queue: ${r.queueCount??"?"}.`);setTimeout(refresh,250);}catch(e){note(e?.message||String(e),true);}};
$("send").onclick=async()=>{const r=await call({type:"BRAIN2_FLUSH"});note(r?.ok?"Queued captures pushed toward Brain2. ACKs remove delivered items.":r?.error||"Send failed",!r?.ok);setTimeout(refresh,250);};
$("clearQueue").onclick=async()=>{if(!confirm("Clear all unsent Brain2 capture queue items?"))return;const r=await call({type:"BRAIN2_CLEAR_QUEUE"});note(r?.ok?`Cleared ${r.removed||0} queued capture(s).`:r?.error||"Clear failed",!r?.ok);setTimeout(refresh,150);};
$("unlock").onclick=async()=>{const r=await call({type:"BRAIN2_UNLOCK",passphrase:$("pass").value});note(r?.ok?"Capture vault unlocked.":r?.error||"Unlock failed",!r?.ok);$("pass").value="";refresh();};
$("lock").onclick=async()=>{await call({type:"BRAIN2_LOCK"});note("Capture vault locked for this browser session.");refresh();};
refresh().catch(e=>note(e?.message||String(e),true));setInterval(()=>refresh().catch(()=>{}),2000);
