import fs from 'node:fs';
const read=(f)=>fs.readFileSync(new URL(f,import.meta.url),'utf8');
const manifest=JSON.parse(read('./manifest.json'));
const adapters=read('./provider_adapters.js');
const capture=read('./capture.js');
const sw=read('./service_worker.js');
const side=read('./sidepanel.js');
const sideHtml=read('./sidepanel.html');
const bridge=read('./bridge.js');
function req(ok,msg){if(!ok)throw new Error(msg);}
req(manifest.version==='0.8.6','version');
for(const host of ['https://chatgpt.com/*','https://claude.ai/*','https://gemini.google.com/*'])req(manifest.host_permissions.includes(host),'provider '+host);
req(!manifest.action?.default_popup,'toolbar popup must be removed');
req(manifest.side_panel?.default_path==='sidepanel.html','side panel');
req(sw.includes('openPanelOnActionClick:true'),'toolbar action must open side panel');
req(sideHtml.includes('Connection')&&sideHtml.includes('Capture'),'two sidebar tabs');
req(sideHtml.includes('panelConnection')&&sideHtml.includes('panelCapture'),'two tab panels');
req(side.includes('chrome.permissions.request'),'connection requests exact site permission');
req(side.includes('BRAIN2_CONFIG_ORIGIN'),'permission continues into bridge config');
req(side.includes('waitForHandshake'),'connection waits for real nonce handshake');
req(side.indexOf('chrome.permissions.request')>=0&&side.indexOf('BRAIN2_CONFIG_ORIGIN')>side.indexOf('chrome.permissions.request'),'one-click permission continuation invariant');
req(sideHtml.includes('id="connectionAction"'),'single connection action button');
req(!sideHtml.includes('id="connect"')&&!sideHtml.includes('id="disconnect"'),'Connect and Disconnect must never coexist as separate buttons');
req(side.includes('action.textContent="Disconnect brain2:inContext"')&&side.includes('action.textContent="Connect to active brain2:inContext tab"'),'single action toggles Connect/Disconnect');
req(side.includes('retryHandshake'),'retry only after configured handshake issue');
req(adapters.includes('version: 2'),'real provider adapter registry v2');
for(const fn of ['conversationId','conversationTitle','isGenerating','extractTurns'])req(adapters.includes(fn),'adapter method '+fn);
req(!capture.includes('provider === "chatgpt"')&&!capture.includes('provider === "claude"'),'capture must be provider-neutral');
req(!capture.includes('chatgpt-semantic-turns')&&!capture.includes('claude-semantic-turns')&&!capture.includes('gemini-semantic-turns'),'provider selectors must live behind adapters');
req(capture.includes('providerAdapter.extractTurns'),'capture delegates extraction');
req(capture.includes('providerAdapter.isGenerating'),'capture delegates generation state');
req(capture.includes('seenFingerprints'),'capture fingerprint engine retained');
req(capture.includes('establishBaseline'),'history baseline retained');
req(capture.includes('BRAIN2_CAPTURE_LATEST'),'manual capture diagnostic retained');
req(sw.includes('BRAIN2_DISCONNECT_WEBSITE'),'disconnect handler');
req(sw.includes('BRAIN2_CAPTURE_LATEST_ACTIVE'),'capture handler');
req(sw.includes('heartbeatFresh'),'live handshake freshness');
req(sw.includes('BRAIN2_WEBSITE_HEARTBEAT'),'website heartbeat handler');
req(sw.includes('files:["provider_adapters.js","capture.js"]'),'fallback injection loads adapter before capture');
req(bridge.includes('BRAIN2_WEBSITE_HEARTBEAT'),'bridge emits heartbeat');
req(bridge.includes('BRAIN2_BRIDGE_RECONNECT'),'reconnect capable bridge');
console.log('Brain2 extension Phase 3 real-adapter + live Connect/Disconnect acceptance PASS');
