"use client";

import { useSyncExternalStore } from "react";
import type { DigestSummary } from "@/lib/contextvault-wasm/loadContextVault";
import type { BrowserDigestStage, BrowserDigestStats, DigestOutputPreview, WorkerEvent } from "@/workers/contextvaultBrowserDigest.worker";

export type V0DigestFileMeta = {
  name: string;
  size: string;
  sizeBytes: number;
  source: string;
};

export type V0DigestLogEntry = {
  id: number;
  stage: BrowserDigestStage;
  message: string;
  percent?: number;
};

export type V0DigestResult = {
  summary: DigestSummary;
  stats: BrowserDigestStats;
  preview: DigestOutputPreview;
  outputZip: Blob;
  outputUrl: string;
  outputFileName: string;
  analysisPrompt: Blob;
  analysisPromptUrl: string;
  analysisPromptFileName: string;
};

export type V0DigestState = {
  file: File | null;
  fileMeta: V0DigestFileMeta | null;
  running: boolean;
  stage: BrowserDigestStage | null;
  progress: number;
  logs: V0DigestLogEntry[];
  result: V0DigestResult | null;
  error: string | null;
};

const initialState: V0DigestState = {
  file: null,
  fileMeta: null,
  running: false,
  stage: null,
  progress: 0,
  logs: [],
  result: null,
  error: null,
};

let state = initialState;
let worker: Worker | null = null;
let logId = 0;
const listeners = new Set<() => void>();

function emit() {
  for (const listener of listeners) {
    listener();
  }
}

function setState(next: Partial<V0DigestState>) {
  state = { ...state, ...next };
  emit();
}

function clearResultUrl() {
  if (state.result?.outputUrl) {
    URL.revokeObjectURL(state.result.outputUrl);
  }
  if (state.result?.analysisPromptUrl) {
    URL.revokeObjectURL(state.result.analysisPromptUrl);
  }
}

function createAnalysisPrompt(summary: DigestSummary, stats: BrowserDigestStats): Blob {
  const sourceOrigin =
    stats.sourceKind === "gemini"
      ? "Google My Activity / Takeout"
      : stats.sourceKind === "claude"
        ? "Claude export"
        : "ChatGPT export";
  const platformNotes =
    stats.sourceKind === "gemini"
      ? [
          "",
          "Source note:",
          "",
          `- This digest came from ${sourceOrigin}.`,
          "- Use activity timestamps and grouped entries when identifying themes, repeated questions, or timelines.",
          "- Treat conversation/group titles and thread structure as approximate because Google Takeout may not preserve true Gemini chat titles or full conversation structure.",
        ]
      : stats.sourceKind === "claude"
        ? [
            "",
            "Source note:",
            "",
            `- This digest came from ${sourceOrigin}.`,
            "- Use conversation titles, message order, and timestamps when identifying workstreams or repeated questions.",
          ]
        : [
            "",
            "Source note:",
            "",
            `- This digest came from ${sourceOrigin}.`,
            "- Use conversation titles, message order, and timestamps when identifying workstreams or repeated questions.",
          ];

  const text = [
    "# AI Chat History Refinery Analysis Prompt",
    "",
    "I uploaded a local digest generated by AI Chat History Refinery.",
    "",
    "Use the attached `index.md` and topic markdown files as the only source of truth.",
    ...platformNotes,
    "",
    "Archive summary:",
    "",
    `- Detected source: ${stats.sourceLabel}`,
    `- Source type: ${stats.sourceType}`,
    `- Conversations or groups: ${stats.conversationCount}`,
    `- Messages or activity items: ${stats.messageCount}`,
    `- Paragraphs: ${summary.paragraphs}`,
    `- Conversation Items: ${summary.atoms}`,
    `- Topic files: ${stats.topicFiles ?? 0}`,
    `- Conversation JSON files scanned: ${stats.jsonFileCount}`,
    "",
    "Please analyze the uploaded digest and produce:",
    "",
    "1. Main recurring themes",
    "2. Important projects or workstreams",
    "3. Repeated questions I asked",
    "4. Unresolved questions or open loops",
    "5. Decisions or conclusions already made",
    "6. Action items and next steps",
    "7. Useful knowledge worth saving",
    "8. Possible timeline of my work",
    "9. Contradictions, duplicate threads, or changes in direction",
    "",
    "Rules:",
    "",
    "- Do not invent facts outside the uploaded files.",
    "- Cite the file name or section when making claims.",
    "- Separate confirmed evidence from inference.",
    "- If evidence is weak, say so.",
    "- Prioritize practical, useful findings.",
    "",
  ].join("\n");

  return new Blob([text], { type: "text/markdown;charset=utf-8" });
}

function appendLog(entry: Omit<V0DigestLogEntry, "id">) {
  setState({ logs: [...state.logs, { ...entry, id: logId++ }] });
}

export function subscribeV0Digest(listener: () => void) {
  listeners.add(listener);
  return () => listeners.delete(listener);
}

export function getV0DigestSnapshot() {
  return state;
}

export function useV0DigestSnapshot() {
  return useSyncExternalStore(subscribeV0Digest, getV0DigestSnapshot, getV0DigestSnapshot);
}

export function setV0DigestFile(file: File, source = "Auto-detect") {
  worker?.terminate();
  worker = null;
  clearResultUrl();
  logId = 0;
  setState({
    file,
    fileMeta: {
      name: file.name,
      size: `${(file.size / 1024 / 1024).toFixed(1)} MB`,
      sizeBytes: file.size,
      source,
    },
    running: false,
    stage: null,
    progress: 0,
    logs: [],
    result: null,
    error: null,
  });
}

export function clearV0DigestRun() {
  worker?.terminate();
  worker = null;
  clearResultUrl();
  logId = 0;
  state = initialState;
  emit();
}

export function cancelV0DigestRun() {
  worker?.postMessage({ type: "cancel" });
  worker?.terminate();
  worker = null;
  appendLog({ stage: "failed", message: "Digest cancelled" });
  setState({ running: false, stage: "failed", error: "Digest cancelled" });
}

export function startV0DigestRun() {
  if (!state.file || state.running) {
    return;
  }

  worker?.terminate();
  worker = new Worker(new URL("../../../workers/contextvaultBrowserDigest.worker.ts", import.meta.url), {
    type: "module",
  });

  clearResultUrl();
  logId = 0;
  setState({
    running: true,
    stage: null,
    progress: 0,
    logs: [],
    result: null,
    error: null,
  });

  worker.onmessage = (event: MessageEvent<WorkerEvent>) => {
    const message = event.data;

    if (message.type === "progress") {
      appendLog({ stage: message.stage, message: message.message, percent: message.percent });
      setState({
        stage: message.stage,
        progress: typeof message.percent === "number" ? message.percent : state.progress,
      });
      return;
    }

    if (message.type === "done") {
      const outputUrl = URL.createObjectURL(message.outputZip);
      const analysisPrompt = createAnalysisPrompt(message.summary, message.stats);
      const analysisPromptUrl = URL.createObjectURL(analysisPrompt);
      setState({
        running: false,
        stage: "completed",
        progress: 100,
        result: {
          summary: message.summary,
          stats: message.stats,
          preview: message.preview,
          outputZip: message.outputZip,
          outputUrl,
          outputFileName: message.outputFileName,
          analysisPrompt,
          analysisPromptUrl,
          analysisPromptFileName: "analysis_prompt.md",
        },
      });
      worker?.terminate();
      worker = null;
      return;
    }

    setState({ running: false, stage: "failed", error: message.error });
    worker?.terminate();
    worker = null;
  };

  worker.onerror = (event) => {
    setState({
      running: false,
      stage: "failed",
      error: event.message || "The browser digest worker failed.",
    });
    worker?.terminate();
    worker = null;
  };

  worker.postMessage({ type: "start", file: state.file });
}
