import { canonicalId, keywords, normalizeText, sha256 } from "./identity";
import { indexedAtomsAsync, indexedMessagesAsync, indexedTruthsAsync, persistentEvidenceExists } from "./retrievalIndex";
import { planRetrieval } from "./retrievalRouter";
import { buildDatabox } from "./databox";
import type { Brain2Snapshot, DataboxRecord } from "./types";
import { assessAtomContextSufficiency, buildB250LocalChunk, BRAIN2_ATOMIZATION_STACK_VERSION } from "./atomizationStack";

export type B2JobEvidence = { id:string; type:"truth"|"atom"|"message"; text:string; projectId?:string; sourceId?:string; conversationId?:string; messageId?:string; blockId?:string; truthStatus?:"CURRENT"|"SUPERSEDED"|"HISTORICAL"|"CONFLICTING"|"UNKNOWN"|"PENDING_REVIEW"; sourceStart?:number; sourceEnd?:number; createdAt?:string; score:number; intrinsicSufficiency?:number };
export type B2JobPackage = {
  format:"B2JOB";version:2;id:string;createdAt:string;question:string;projectId?:string;memoryRoot:string;evidenceHash:string;databox:DataboxRecord;
  evidencePolicy:{limit:number;method:"asif-reader-rapidretrieve-v9";route:string;fallback?:string;boundedContext:true;candidateCap:number;atomizationStack:string;sufficiencyScore:number;sufficiencyState:"SUFFICIENT"|"AMBIGUOUS"|"INSUFFICIENT";usedB250Fallback:boolean};instructions:string[];evidence:B2JobEvidence[];
};
export type B2ResultPackage = {format:"B2RESULT";version:1|2;jobId:string;answer:string;evidenceIds:string[];databoxHash?:string;model?:string;createdAt?:string};
function scoreText(text:string,queryTerms:string[],exactQuery:string){const normalized=normalizeText(text).toLowerCase();let score=exactQuery&&normalized.includes(exactQuery)?5:0;for(const term of queryTerms)if(normalized.includes(term))score+=1;return score;}
function diversityKey(item:B2JobEvidence){return `${item.projectId??"none"}|${item.sourceId??"none"}|${item.type}`;}

export async function compileB2Job(snapshot:Brain2Snapshot,question:string,projectId?:string,limit=24):Promise<B2JobPackage>{
  const q=normalizeText(question);if(!q)throw new Error("Enter a question or task first.");
  const plan=planRetrieval(q);const terms=keywords(q,16);const exact=q.toLowerCase();const candidates:B2JobEvidence[]=[];const conversationById=new Map(snapshot.conversations.map((item)=>[item.id,item]));
  for(const truth of await indexedTruthsAsync(snapshot,q,plan.candidateCap,projectId)){if(!["CURRENT","CONFLICTING","PENDING_REVIEW"].includes(truth.status)||(projectId&&truth.projectId!==projectId))continue;const currentBoost=truth.status==="CURRENT"?plan.truthBoost:truth.status==="CONFLICTING"?1.3:.6;const score=scoreText(truth.text,terms,exact)+currentBoost+truth.confidence;if(score<=2&&terms.length)continue;candidates.push({id:truth.id,type:"truth",text:truth.text,projectId:truth.projectId,truthStatus:truth.status,createdAt:truth.updatedAt,score});}
  for(const atom of await indexedAtomsAsync(snapshot,q,plan.candidateCap,projectId)){if(projectId&&atom.projectId!==projectId)continue;const score=scoreText(atom.text,terms,exact)+atom.confidence+(["decision","constraint"].includes(atom.kind)?0.8:0);if(score<=1&&terms.length)continue;candidates.push({id:atom.id,type:"atom",text:atom.text,projectId:atom.projectId,sourceId:atom.sourceId,conversationId:atom.conversationId,messageId:atom.messageId,sourceStart:atom.sourceStart,sourceEnd:atom.sourceEnd,createdAt:atom.createdAt,score,intrinsicSufficiency:atom.intrinsicSufficiency} as B2JobEvidence & {intrinsicSufficiency?:number});}
  candidates.sort((a,b)=>b.score-a.score||(b.createdAt??"").localeCompare(a.createdAt??"")||a.id.localeCompare(b.id));
  const target=Math.max(1,Math.min(64,limit));const dedup=new Map<string,B2JobEvidence>();const diversity=new Map<string,number>();
  for(const candidate of candidates){const textKey=normalizeText(candidate.text).toLowerCase();if(dedup.has(textKey))continue;const dkey=diversityKey(candidate);const seen=diversity.get(dkey)??0;const adjusted={...candidate,score:candidate.score-(seen*plan.diversityBoost*.15)};dedup.set(textKey,adjusted);diversity.set(dkey,seen+1);if(dedup.size>=target)break;}
  let evidence=[...dedup.values()].sort((a,b)=>b.score-a.score);
  const sufficiency=assessAtomContextSufficiency({query:q,evidence:evidence.map((item)=>({text:item.text,score:item.score,type:item.type,truthStatus:item.truthStatus,intrinsicSufficiency:(item as B2JobEvidence & {intrinsicSufficiency?:number}).intrinsicSufficiency}))});
  const usedB250Fallback=sufficiency.state!=="SUFFICIENT";
  if(usedB250Fallback){
    const fallbackCandidates:B2JobEvidence[]=[];
    for(const message of await indexedMessagesAsync(snapshot,q,Math.min(96,plan.candidateCap),projectId)){
      const conversation=conversationById.get(message.conversationId);if(projectId&&conversation?.projectId!==projectId)continue;
      const matchStart=Math.max(0,message.text.toLowerCase().indexOf(exact));const chunk=buildB250LocalChunk(message.text,matchStart,matchStart+Math.max(1,q.length));if(!chunk.text)continue;
      const score=scoreText(chunk.text,terms,exact)+(message.role==="user"?.5:0);if(score<=.5&&terms.length)continue;
      const blockId=await canonicalId("b250-local",message.id,chunk.sourceStart,chunk.sourceEnd);
      fallbackCandidates.push({id:message.id,type:"message",text:chunk.text,projectId:conversation?.projectId,sourceId:message.sourceId,conversationId:message.conversationId,blockId,sourceStart:chunk.sourceStart,sourceEnd:chunk.sourceEnd,createdAt:message.occurredAt??message.createdAt,score:score+.35});
      if(fallbackCandidates.length>=Math.max(4,Math.ceil(target/2)))break;
    }
    const merged=new Map<string,B2JobEvidence>();for(const item of [...evidence,...fallbackCandidates]){const key=`${item.id}|${item.sourceStart??0}|${item.sourceEnd??0}`;if(!merged.has(key))merged.set(key,item);}evidence=[...merged.values()].sort((a,b)=>b.score-a.score).slice(0,target);
  }
  const databox=await buildDatabox({snapshot,query:q,projectId,retrievalRoute:usedB250Fallback?`${plan.route}+B_250_CHUNK`:plan.route,evidence});const createdAt=new Date().toISOString();const id=await canonicalId("b2job-v2",snapshot.memoryRoot,q,projectId,databox.hash,createdAt);const evidenceHash=databox.evidenceHash;
  return{format:"B2JOB",version:2,id,createdAt,question:q,projectId,memoryRoot:snapshot.memoryRoot,evidenceHash,databox,evidencePolicy:{limit:evidence.length,method:"asif-reader-rapidretrieve-v9",route:plan.route,fallback:usedB250Fallback?"B_250_CHUNK":plan.fallback,boundedContext:true,candidateCap:plan.candidateCap,atomizationStack:BRAIN2_ATOMIZATION_STACK_VERSION,sufficiencyScore:sufficiency.score,sufficiencyState:sufficiency.state,usedB250Fallback},instructions:["Use the attached B2DATABOX as the authoritative minimum sufficient context.","Preserve uncertainty and conflicts; do not silently choose one side of CONFLICTING evidence.","Return format=B2RESULT version=2 with jobId, databoxHash, answer, and only evidenceIds actually used from this B2JOB.","If the Databox is insufficient, state the evidence gap instead of inventing facts.","Memory writes are proposals only; no reasoning result directly mutates Current Truth."],evidence};
}

export function parseB2Result(value:unknown):B2ResultPackage{if(!value||typeof value!=="object")throw new Error("Result must be a JSON object.");const result=value as Partial<B2ResultPackage>;if(result.format!=="B2RESULT"||(result.version!==1&&result.version!==2)||typeof result.jobId!=="string"||typeof result.answer!=="string"||!Array.isArray(result.evidenceIds)||!result.evidenceIds.every((id)=>typeof id==="string"))throw new Error("Unsupported B2RESULT.");if(result.version===2&&typeof result.databoxHash!=="string")throw new Error("B2RESULT v2 requires databoxHash.");return result as B2ResultPackage;}

export function verifyB2Result(snapshot:Brain2Snapshot,result:B2ResultPackage){
  const uniqueEvidenceIds=[...new Set(result.evidenceIds)];const jobTx=[...snapshot.transactions].reverse().find((tx)=>tx.type==="B2JOB"&&(()=>{try{return JSON.parse(tx.payload)?.id===result.jobId}catch{return false}})());let job:B2JobPackage|undefined;try{job=jobTx?JSON.parse(jobTx.payload) as B2JobPackage:undefined}catch{}
  const allowed=new Set(job?.evidence?.map((item)=>item.id)??[]);const known=new Set([...snapshot.truths.map((item)=>item.id),...snapshot.atoms.map((item)=>item.id),...snapshot.messages.map((item)=>item.id)]);const missingEvidenceIds=uniqueEvidenceIds.filter((id)=>!known.has(id));const outsideJobEvidenceIds=uniqueEvidenceIds.filter((id)=>known.has(id)&&!allowed.has(id));const memoryRootMatches=!job||job.memoryRoot===snapshot.memoryRoot;const databoxMatches=!job||result.version===1||result.databoxHash===job.databox?.hash;
  const status=!job||!memoryRootMatches||!databoxMatches||missingEvidenceIds.length||outsideJobEvidenceIds.length?"FAIL":uniqueEvidenceIds.length?"PASS":"PENDING";
  return{status:status as "PASS"|"FAIL"|"PENDING",jobExists:Boolean(job),memoryRootMatches,databoxMatches,citedEvidenceCount:uniqueEvidenceIds.length,missingEvidenceIds,outsideJobEvidenceIds,detail:!job?"The referenced B2JOB is not present in this local memory.":!memoryRootMatches?"The B2RESULT references a B2JOB from a different Brain2 memory root.":!databoxMatches?"B2RESULT Databox hash does not match the canonical B2JOB context package.":missingEvidenceIds.length?`Result cites ${missingEvidenceIds.length} evidence ID(s) that do not exist in this local memory.`:outsideJobEvidenceIds.length?`Result cites ${outsideJobEvidenceIds.length} real Brain2 evidence ID(s) that were not supplied inside the referenced B2JOB.`:uniqueEvidenceIds.length?`V7 structural provenance PASS: Databox lineage matches and all ${uniqueEvidenceIds.length} cited evidence ID(s) belong to the referenced B2JOB.`:"No evidence IDs were cited."};
}

export async function verifyB2ResultAsync(snapshot:Brain2Snapshot,result:B2ResultPackage){
  const uniqueEvidenceIds=[...new Set(result.evidenceIds)];const jobTx=[...snapshot.transactions].reverse().find((tx)=>tx.type==="B2JOB"&&(()=>{try{return JSON.parse(tx.payload)?.id===result.jobId}catch{return false}})());let job:B2JobPackage|undefined;try{job=jobTx?JSON.parse(jobTx.payload) as B2JobPackage:undefined}catch{}
  const allowed=new Set(job?.evidence?.map((item)=>item.id)??[]);const hotKnown=new Set([...snapshot.truths.map((item)=>item.id),...snapshot.atoms.map((item)=>item.id),...snapshot.messages.map((item)=>item.id)]);const coldKnown=await persistentEvidenceExists(uniqueEvidenceIds.filter((id)=>!hotKnown.has(id)));const exists=(id:string)=>hotKnown.has(id)||coldKnown.has(id);const missingEvidenceIds=uniqueEvidenceIds.filter((id)=>!exists(id));const outsideJobEvidenceIds=uniqueEvidenceIds.filter((id)=>exists(id)&&!allowed.has(id));const memoryRootMatches=!job||job.memoryRoot===snapshot.memoryRoot;const databoxMatches=!job||result.version===1||result.databoxHash===job.databox?.hash;const status=!job||!memoryRootMatches||!databoxMatches||missingEvidenceIds.length||outsideJobEvidenceIds.length?"FAIL":uniqueEvidenceIds.length?"PASS":"PENDING";return{status:status as "PASS"|"FAIL"|"PENDING",jobExists:Boolean(job),memoryRootMatches,databoxMatches,citedEvidenceCount:uniqueEvidenceIds.length,missingEvidenceIds,outsideJobEvidenceIds,detail:!job?"The referenced B2JOB is not present in this local memory.":!memoryRootMatches?"The B2RESULT references a B2JOB from a different Brain2 memory root.":!databoxMatches?"B2RESULT Databox hash does not match the canonical B2JOB context package.":missingEvidenceIds.length?`Result cites ${missingEvidenceIds.length} evidence ID(s) that do not exist in this local memory.`:outsideJobEvidenceIds.length?`Result cites ${outsideJobEvidenceIds.length} real Brain2 evidence ID(s) that were not supplied inside the referenced B2JOB.`:uniqueEvidenceIds.length?`V7 provenance PASS across hot + cold memory: all ${uniqueEvidenceIds.length} cited evidence ID(s) belong to the referenced B2JOB.`:"No evidence IDs were cited."};
}
