import type { AtomRecord, PatternRecord, PatternTestRecord, TruthRecord } from "./types";
import { BRAIN2_PATTERN_VERSION } from "./contracts";
import { canonicalId, normalizeText } from "./identity";
import { evaluatePattern } from "./patternLab";

export type PatternAggregate = {patternKey:string;label:string;kind:string;evidenceCount:number;projectIds:Set<string>;atomIds:string[];counterexampleAtomIds:string[]};
export function patternKeyForAtom(atom:AtomRecord):string{const subject=normalizeText(atom.canonicalSubject||atom.subject).toLowerCase();const terms=(subject||atom.keywords.slice(0,3).sort().join(" ")).split(" ").filter(Boolean).slice(0,4).sort();return `${atom.kind}:${terms.join("-")||"unresolved"}`;}
export function patternLabelForAtom(atom:AtomRecord):string{const subject=normalizeText(atom.subject||atom.canonicalSubject||atom.keywords.slice(0,3).join(" "));return subject||`${atom.kind} pattern`;}
export function accumulatePattern(map:Map<string,PatternAggregate>,atom:AtomRecord,conflictingAtomIds:Set<string>){if(!["decision","constraint","fact","task","idea"].includes(atom.kind))return;const patternKey=patternKeyForAtom(atom);const aggregate=map.get(patternKey)??{patternKey,label:patternLabelForAtom(atom),kind:atom.kind,evidenceCount:0,projectIds:new Set<string>(),atomIds:[],counterexampleAtomIds:[]};aggregate.evidenceCount+=1;aggregate.projectIds.add(atom.projectId);aggregate.atomIds.push(atom.id);if(aggregate.atomIds.length>300)aggregate.atomIds.shift();if(conflictingAtomIds.has(atom.id)){aggregate.counterexampleAtomIds.push(atom.id);if(aggregate.counterexampleAtomIds.length>100)aggregate.counterexampleAtomIds.shift();}map.set(patternKey,aggregate);}
export async function buildPatternsFromAggregates(aggregates:Iterable<PatternAggregate>,limit=250,tests:PatternTestRecord[]=[]):Promise<PatternRecord[]>{const patterns:PatternRecord[]=[];for(const group of aggregates){if(group.evidenceCount<3)continue;const evidenceCount=group.evidenceCount;const crossProject=group.projectIds.size;const counterexampleRatio=group.counterexampleAtomIds.length/Math.max(1,evidenceCount);const strength=Math.max(0,Math.min(1,.28+Math.log2(evidenceCount+1)/9+Math.min(.24,crossProject*.06)-counterexampleRatio*.45));let status:PatternRecord["status"]="OBSERVED";let verificationStatus:PatternRecord["verificationStatus"]="UNTESTED";let maturity:NonNullable<PatternRecord["maturity"]>="L1_OBSERVATION";if(evidenceCount>=3)maturity="L2_CANDIDATE";if(evidenceCount>=7&&crossProject>=2){status="CANDIDATE";maturity="L3_HYPOTHESIS";}if(evidenceCount>=12&&crossProject>=2){status="TESTING";verificationStatus=group.counterexampleAtomIds.length?"COUNTEREXAMPLE_FOUND":"NEEDS_TRANSFER_TEST";}let pattern:PatternRecord={id:await canonicalId("pat",group.patternKey),label:group.label,status,strength,projectIds:[...group.projectIds],atomIds:group.atomIds,evidenceCount,counterexamples:group.counterexampleAtomIds.length,counterexampleAtomIds:group.counterexampleAtomIds,hypothesis:`Repeated ${group.kind||"knowledge"} structure around ${group.label}.`,boundaryConditions:crossProject<2?["Observed in only one project"]:[],verificationStatus,patternKey:group.patternKey,patternVersion:BRAIN2_PATTERN_VERSION,updatedAt:new Date().toISOString(),maturity,falsificationStatus:"UNTESTED",predictions:[]};const evaluation=evaluatePattern(pattern,tests);pattern={...pattern,status:evaluation.status,maturity:evaluation.maturity,verificationStatus:evaluation.verificationStatus,falsificationStatus:evaluation.falsificationStatus,transferTestIds:evaluation.transferTestIds,boundaryConditions:evaluation.boundaryConditions,strength:Math.max(pattern.strength,evaluation.supportScore)};patterns.push(pattern);}return patterns.sort((a,b)=>b.strength-a.strength||b.evidenceCount-a.evidenceCount).slice(0,limit);}
export async function buildPatterns(atoms:AtomRecord[],truths:TruthRecord[],limit=250,tests:PatternTestRecord[]=[]):Promise<PatternRecord[]>{const conflicts=new Set(truths.filter((truth)=>truth.status==="CONFLICTING").flatMap((truth)=>truth.evidenceAtomIds??[truth.atomId]));const aggregates=new Map<string,PatternAggregate>();for(const atom of atoms)accumulatePattern(aggregates,atom,conflicts);return buildPatternsFromAggregates(aggregates.values(),limit,tests);}
